Feature/get all
marketredesign/mrd-auth0-laravel pull request #12
Opened 2021-10-13 11:30 UTC by KadirMarangoz

## Proposed changes

Added support for a `getAllUsers` through the Auth0 Management API to both real and fake User facade including tests.

## Types of changes

What types of changes does your code introduce to this repository?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Unit testing

Run vendor/bin/phpunit from the project root

### Manual testing

Not Applicable

2021-10-17 15:05 UTC, marijnvanderhorst requested changes
Looks good, some small comments

2021-10-17 15:05 UTC, marijnvanderhorst commented on tests/Feature/UserRepositoryTest.php
> +    public function testGetAllUsers()
Please add a PhpDoc comment

2021-10-17 15:05 UTC, marijnvanderhorst commented on tests/Feature/UserRepositoryTest.php
> +        // Expect one user returned.
```suggestion
        // Expect two users returned.
```

2021-10-20 10:59 UTC, KadirMarangoz commented on tests/Feature/UserRepositoryTest.php
> +    public function testGetAllUsers()
Fixed

2021-10-20 17:52 UTC, marijnvanderhorst commented on src/Contracts/UserRepository.php
> +     * @param array|null $fields Fields to be retrieved for each user.
Comment above it is still incorrect: "optionally limited..."

2021-10-20 17:55 UTC, marijnvanderhorst approved these changes
Looks good 👍

2021-10-20 17:56 UTC, merged