Add middleware to check permissions of logged in user
marketredesign/mrd-auth0-laravel pull request #19
Opened 2022-01-07 16:48 UTC by SquarePlayn

## Proposed changes

This PR adds a middleware class `CheckPermission`, usable as middleware `permission:{permission}`, that can be used to protect a route to ensure that the user is logged in and has a certain Auth0 permission.

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
### Unit testing
As usual

### Manual testing
Use the package in a laravel app and protect an endpoint with the permissions middleware.

## Further comments

2022-01-17 12:39 UTC, marijnvanderhorst requested changes
Please update the readme as well with a short explanation on how to use this new middleware.

2022-01-17 12:39 UTC, marijnvanderhorst commented on src/Http/Middleware/CheckPermissions.php
> +        $token = Auth::user()->getAuthPassword();
To me it doesn't really make sense to use the access token for this purpose. The access token should be used to access resources on behalf of the user. What we are doing here is checking the permissions of the logged-in user, which should be performed using the ID token instead, right? (following the OpenID connect protocol)

2022-03-22 10:22 UTC, marijnvanderhorst approved these changes
Accepting my own changes.. :)

2022-03-22 16:57 UTC, SquarePlayn commented
> @SquarePlayn I've updated it to use the ID token (/ userinfo) now instead of the Bearer token. Please check whether you agree with my changes.

I have made some small changes to the tests, which contained something with the JWT token that is not needed anymore and made one test a little stronger of a test. Other than that, looks good, thanks for the help!

2022-03-24 07:57 UTC, marijnvanderhorst approved these changes

2022-03-24 16:06 UTC, merged