Dataset authorization
marketredesign/mrd-auth0-laravel pull request #7
Opened 2021-04-10 14:38 UTC by marijnvanderhorst

**This is a public package, in a public repository**

## Proposed changes
Adds a middleware to authorize datasets. The underlying dataset repository is also exposed (using a facade) such that it can be used by applications using this package to retrieve the datasets a user has access to as well.

## Types of changes

What types of changes does your code introduce to this repository?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing
Explain here how to run your unit tests, and explain how to execute manual testing. 

### Unit testing
Added.

### Manual testing
Use in laravel application, add dataset auth middleware (see readme) and verify that dataset access is authorized properly.

## Further comments
n/a

2021-04-10 17:09 UTC, SquarePlayn requested changes
Works well in general. Some small comments and an important exploit:

If you have a route that has a dataset ID in the route itself, you can also provide a dataset ID as parameter. The route ID is then used for authentication, while the parameter is the one actually used (that gets send to the controller). E.g. User X has access to DS 1. Requesting `/api/dataset/1/secrets?datasetId=5` can give user X access to a response for dataset 5.

Here is the test setup I used:
```
Route::middleware('jwt:read:datasets')->middleware('dataset.access')->get('/test/{datasetId}/secret', function ($datasetId) {
    return 'Response for Dataset ' . $datasetId;
});
```
With which `localhost/api/test/233/secret` correctly fails (no authorization on 233), but `localhost/api/test/233/secret?datasetId=5` (incorrectly) returns `Response for Dataset 233`.

2021-04-10 17:09 UTC, SquarePlayn commented on config/mrd-auth0.php
> +    // 'guzzle_options' => []
In fact, it's giving me error 500 results because the guzzle_options parameter is not an array. So I think this should be uncommented.

2021-04-11 13:31 UTC, marijnvanderhorst commented on tests/Feature/DatasetAuthorizationTest.php
> +        $app['config']->set('mrd-auth0.guzzle_options', $this->createTestingGuzzleOptions());
This is how I always do it in the `getEnvironmentSetUp()`.

2021-04-11 13:32 UTC, marijnvanderhorst commented on src/Repository/Fakes/FakeDatasetRepository.php
> +     * Gets a random dataset object for the given ID, which will be created if it does not already exist.
You're right. Changed the function name as well.

2021-04-11 13:33 UTC, marijnvanderhorst commented
> Works well in general. Some small comments and an important exploit:
> 
> If you have a route that has a dataset ID in the route itself, you can also provide a dataset ID as parameter. The parameter ID is then used for authentication, while the route one is the one actually used (that gets send to the controller). E.g. User X has access to DS 5. Requesting `/api/dataset/1/secrets?datasetId=5` can give user X access to a response for dataset 1.
> 
> Here is the test setup I used:
> 
> ```
> Route::middleware('jwt:read:datasets')->middleware('dataset.access')->get('/test/{datasetId}/secret', function ($datasetId) {
>     return 'Response for Dataset ' . $datasetId;
> });
> ```
> 
> With which `localhost/api/test/233/secret` correctly fails (no authorization on 233), but `localhost/api/test/233/secret?datasetId=5` (incorrectly) returns `Response for Dataset 233`.

Very very very good catch!! Thanks a lot. I've updated the implementation and added tests for it.

2021-04-11 13:33 UTC, marijnvanderhorst commented on config/mrd-auth0.php
> +    // 'guzzle_options' => []
Uncommented

2021-04-11 13:33 UTC, marijnvanderhorst commented on src/Repository/DatasetRepository.php
> +     * Send GET request to a REST API.
Updated docs

2021-04-11 13:33 UTC, marijnvanderhorst commented on src/Repository/DatasetRepository.php
> +     * @param array $options extra options to send in the request, like query parameters.
Updated docs

2021-04-11 16:40 UTC, SquarePlayn approved these changes
Thanks for the changes.

2021-04-12 00:38 UTC, merged